version: "3"
services:
    web:
        build: .
        restart: unless-stopped
        ports:
            - "3000:3000"
    mongo:
        image: mongo:latest
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "27017:27017"
